#logging:
#  level:
#    com.train.base: debug
spring:
  application:
    name: voucher-java-demo
  datasource:
    url: jdbc:h2:~/database/h2/demo.db
    driver-class-name: org.h2.Driver
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
server:
  port: 8090
  error:
    include-message: ALWAYS
  forward-headers-strategy: framework